# Project information
site_name: Kotlinq
site_description: GraphQL DSLs for Kotlin
site_author: Preston Garno
site_url: http://prestongarno.github.io/kotlinq

# Repository
repo_name: prestongarno/kotlinq
repo_url: https://github.com/prestongarno/kotlinq

# Copyright
copyright: 'Copyright &copy; 2017 Preston Garno'

# Theme directory
theme: material

docs_dir: docs

# Options
extra:
  palette:
    primary: #003366
    accent: pink
  social:
    - type: globe
      link: http://prestongarno.com
    - type: github-alt
      link: https://github.com/prestongarno
    - type: twitter
      link: https://twitter.com/preston_dev
    - type: linkedin
      link: https://linkedin.com/in/prestongarno

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=true)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

# Page tree
pages:
  - Intro: index.md
  - Hello, world!: hello_world.md
  - Getting started: getting-started.md
  - Types:
    - Introduction: types/paradigms.md
    - Primitives/Scalars: types/primitives.md
    - Custom Scalars: types/custom_scalars.md
    - Objects: types/objects.md
    - Nullables: types/nullables.md
  - API:
    - Query: api/query.md
    - Mutation: api/mutation.md
    - Subscription: subscription.md
  - HTTP: http.md
  - FAQ: faq.md
  - Release notes: release_notes.md
  - Contributing: contributing.md
  - License: license.md

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
